### PR TITLE
Adds RSS feeds -- proposes fix for #4

### PR DESCRIPTION
**Pull request by compleatang**

### CODE REVIEW

**Comment by konklone** [comment]
This is great! There is one issue though, which is that this is suggesting using the raw.github.com URL for the XML file, and that means the XML feed needs to get versioned in Github and pushed up to the server (like `fisa.html` does), for those updates to appear on the web. Right now, it just gets written to disk, and so the raw.github.com URL will never change.

My original idea wasn't to do that, though, but rather to expect someone to put a webserver like nginx or Apache up in front of it, and serve the static file. Or, maybe Amazon S3 integration would make sense, have it auto-upload. I'm not 100% closed to the idea of using raw.github.com URLs, but it's not ideal technically (Github doesn't do mime-types for raw URLs), and Github doesn't want people plugging raw.github.com URLs into anythng, because it doesn't hit their static file server.

I could merge this with the code unchanged, if the docs dropped the references to using raw.github.com URLs and encouraged the user to serve the file their own way.

**Comment by compleatang** [comment]
I dIdn't realize that it was bad form to link to raw.github.com. That is good to know. I was trying to get around the requirement for users to run their own server and that seemed the easiest to me. I did not add the .xml to the .gitignore so when I tested it, the .xml was committed with the .html and pushed. I just double checked tonight and the way I structured the call, though, is that even if the xml were in the repo it would be a commit behind.

It seems to me the structure of building the new RSS entry after the script has received the Github diff link is probably the better way to go, so I'll also add the .xml file to the .gitignore.

**Comment by konklone** [comment]
I wonder if we could (ab)use the GitHub Releases system for publishing an
RSS feed through their static file server, without committing another file
to source control? Would mean interacting with the GitHub API.

**Comment by compleatang** [comment]
When I was trying to figure out how this could work best it occurred to me that we probably don't need to worry about either my first way or the releases way if someone was on Github. GH already deploys a commits feed. If a user was using GH, they can just subscribe to https://github.com/USER/REPO/commits.atom and _xallas_; finished. 

It is those wanting an RSS feed and not on GH that is the case that I refactored the branch to address. Let me know what you think. Tomorrow I'll work on the downloads branch and see if I can address your very valid concerns there. 

I made a few minor tweaks to the script, added the xml file to the gitignore, and updated the readme with some chat on how to deploy for RSS. I'm almost wondering if the readme should be simplified for this section as non-technical users will probably not be deploying to their own web server and technical users should be able to roll their own vhost.

At any rate, always easier to delete than to add.

**Comment by konklone** [comment]
I hadn't thought of those commit feeds - and you don't need to be a Github user to use them, they're publicly accessible. But what I'd _really_ want is a commit feed filtered down to the [history of fisa.html](https://github.com/konklone/fisa/commits/master/fisa.html), so that my own updates to, like, the README, don't appear in the feed of someone watching the actual Court.

Alternate idea: use Github Pages. `fisa.xml` (and maybe `fisa.html` too) could be versioned in a gh-pages branch, and then it would be accessible through Github's static file server in a sanctioned, efficient manner. I think this might be the winning approach. It's just a little less obvious what's happening to less technical people, since branch switching does all this invisible work.

**Comment by compleatang** [comment]
You're right. The feed should be filtered. I'll update the README to advise users that the commit feed will include all the commits they make. If a user had their own script and didn't make any other changes it should be fine, but if they wanted to follow your script it would not work well.

The idea of using GH pages is probably the winner. Avoids having to set up your own server for simply the xml file and would filter the content appropriately. If a user had downloaded the pdfs you could also consider committing those into the GH pages branch so they could be mirrored publicly. Not sure if that would be abuse of GH's disk space and bandwidth, but it would be easy enough to do.

Pushing to an alternate branch could also help solve some of the problems I was having when I was testing this branch last night with my repo history (although now I understand what reflog is and how to use it which is good for my learning). I will see what I can put together in a few days as am travelling tonight/tomorrow.

**Comment by konklone** [comment]
Why don't you let me refactor to move fisa.html to gh-pages this weekend
first - then it'll be easier to work in a new file in the same branch.

**Comment by compleatang** [comment]
Sounds good. I'll catch up early next week.

**Comment by konklone** [comment]
Actually, no need for a `fisa.xml` if `fisa.html` is on its own branch, and no need for it to use `gh-pages`, because you can get Atom feeds for commits per-branch, e. g.:

https://github.com/konklone/fisa/commits/test.atom

So as long as the main FISA commits are in their own branch, then Github gives us a free Atom feed, independent of their GH pages architecture. Keeps this script's code a lot simpler, too.

Given that, I'm going to close this PR and drop a reference to #4 so that it links here to this description.

**Comment by compleatang** [comment]
Cool.

**Comment by konklone** [comment]
This is such a weird thing to tackle, since the script runs out of its own repository, and branch-switching would switch the code out from under itself. PRs are welcome for it, but for the time being I'm going to focus on making this app self-hostable via [Docker](http://www.docker.io).

**Pull request closed without merging**
