### PR TITLE
WIP: Inject some Rubyisms

### PR DESCRIPTION
**Pull request by benbalter**
What started out as a fix for https://github.com/konklone/fisacourt/issues/24 has taken a terrible turn for the worse. Cleaning up in a big way, but surfacing here for early feedback. 

Primary goal was to more closely follow common Ruby idioms to make things a bit more maintainable.

Also, naming things are hard.
- [ ] Alerting
- [ ] CLI
- [ ] Verify it actually works
- [ ] Set up pushing (just need to add a single `agent.sync` call at the end)
- [ ] Maybe add tests

### CODE REVIEW

**Comment by benbalter** [comment]
@konklone this is in a solid place if you want to take a look. Have a todo list above (notably CLI and alerting), but wanted to surface for feedback to see if it was worth continuing in this direction before investing more time. :thought_balloon:?

**Comment by benbalter** [comment]
To note, the main goal here was to decentralize the logic (so e.g., a filing knows if it was updated, not the check method), and to get away from a single, functional method as much as possible. Dat complexity. A few things to call out:
- Use Change Agent, so we manipulate the git DB directly, and never actually touch the file system directly
- Use Typheous for better error handling, simplicity of use, cross-platform support, and most importantly, eventual parallelization of requests
- Made everything into objects (e.g., a `Filing` knows it's own ID, PDF URL, etc.)
- Use standard Ruby libs for things like calculating checksums (no more shelling out)
- Memoize all the things!
- Smarter debug output (via inspect and native ruby Logger (which can be disabled in Prod))
- Ruby style dictates you don't use bang methods unless you have a non-bang method
- Extremely simplified check logic (since filings now know a lot about themselves)
- Added `script/console` (and pry) for easier debugging

**Comment by konklone** [comment]
Thanks to the moon and back for tackling this, @benbalter. This thing became a rat's nest, and has not been working. I'm psyched to get this in working order.

> most importantly, eventual parallelization of requests

Typhoeus sounds like a good move, but fwiw I'm hesitant to ever introduce parallelization. Speed of downloading the corpus is not as important as not getting myself banned. :smile_cat: 

> Ruby style dictates you don't use bang methods unless you have a non-bang method

Then Ruby style is dumb!

Anyway, reviewing in more detail now. :santa:

**Comment by konklone** [comment]
Closing ahead of repo archiving.

**Pull request closed without merging**
